import re

def extract_questions(text :str)->list[str]:
    """
    test on questions content generated by llama 3.2 3B-instruct
    """
    # 这条正则会匹配“数字 + 点 + 空格”开始到下一个同样格式的编号（或文本结尾）之间的全部内容
    # ?= 表示正向预查，不消耗字符串
    # $ 表示字符串的结尾
    pattern = r"\d+\.\s+(.*?)(?=\n\d+\.\s+|$)"

    # 使用 DOTALL 标志让 “.” 能匹配换行符
    questions = re.findall(pattern, text, flags=re.DOTALL)

    # 去除可能多余的前后空白
    questions = [q.strip() for q in questions]

    return questions

if __name__ == '__main__':
    text = """**Answer 1:**
Here are the word problems:

1. A school is planning a field day event where students will be divided into teams to participate in various games. If there are 45 students in total, and each team should have an equal number of boys and girls, how many students should be on each team?

2. In a rectangular garden measuring 30 meters by 25 meters, what is the area of the rectangle that can be planted with flowers? The rest of the garden must remain unpaved.

3. What is the value of x in the equation 3x^2 + 12x - 21 = 0?

4. A bakery sells 250 loaves of bread per day, and they use a recipe that yields 20% more bread than the amount used the previous day. How many loaves did they make yesterday?

5. A car travels from city A to city B at an average speed of 60 miles per hour. On the return trip, it takes 50% longer than the first leg of the trip. What is the distance between the two cities?

6. A company has three branches, and each branch has 15 employees. If two employees are transferred from one branch to another, how many employees does the company have after the transfer?

7. In a game of chance, you roll a die and bet that the number that appears is even or odd. You lose if the number is neither even nor odd (i.e., it's 6). What is your expected payout if you win $10 for even numbers, $5 for odd numbers, and -$100 for rolling a 6?

8. A pipe can fill a tank in 6 hours. However, due to a leak, the tank is filled in 8 hours instead. How long would it take to fill the tank without the leak?

9. A bookstore has a shelf containing 500 books. Each week, they remove 25% of the oldest books and replace them with 10 new ones. After four weeks, what percentage of the original books are still on the shelf?
"""
    questions = extract_questions(text)
    for i, question in enumerate(questions):
        print(f'{i}: {question}')
